starting_deposition_number: 0
final_deposition_number: 3
work_directory: testing
run_with_mpi: False
max_cores: 8
insert_distance: 20.0 #angstrom 
contact_tolerance: 4.0 #angstrom 
escape_tolerance: 20.0 #angstrom 
time_step: 0.004 #ps
drift_velocity: 0.8 #nm/ps
deposition_steps:
  - description: "Initial deposition of a full mixture of CBP"
    first_sim_id: 1
    last_sim_id:  1
    run_time: 0.5 #ps
    temperature: 300 #K
    mixture:
      CBP:
        res_name: CBP
        pdb_file: templates/CBP.pdb
        itp_file: templates/CBP.itp
        ratio: 1
  - description: "Second deposition of a mixture of IPR and IPS"
    first_sim_id: 2
    last_sim_id:  2
    run_time: 1.5 #ps
    temperature: 300 #K
    mixture:
      IPR:
        res_name: IPR
        pdb_file: templates/IPR.pdb
        itp_file: templates/IPR.itp
        ratio: 1
      IPS:
        res_name: IPS
        pdb_file: templates/IPS.pdb
        itp_file: templates/IPS.itp
        ratio: 1
  - description: "Final deposition of a mixture of a single CBP molecule"
    first_sim_id: 3
    last_sim_id:  3
    run_time: 1.5 #ps
    temperature: 300 #K
    mixture:
      BCP:
        res_name: BCP
        pdb_file: templates/BCP.pdb
        itp_file: templates/BCP.itp
        ratio: 1
substrate: 
      res_name: GRP
      pdb_file: templates/GRP.pdb
      itp_file: templates/GRP.itp
movies:
    n_cores: 8
