starting_deposition_number: 0
final_deposition_number: 1202
work_directory: /mddata/uqmstroe/phaseTransitionData/slowRun
run_with_mpi: True
max_cores: 16
insert_distance: 40.0 #angstrom 
contact_tolerance: 4.0 #angstrom 
escape_tolerance: 20.0 #angstrom 
time_step: 0.004 #ps
drift_velocity: 0.08 #nm/ps
deposition_steps:
  - description: 'Initial Deposition of a 1000 CBP/IPR-IPS (42:1:1 ratio) (~10nm high) molecules'
    first_sim_id: 0
    last_sim_id: 1000
    run_time: 50.0 #ps
    temperature: 300
    mixture:
        CBP:
          res_name: CBP
          pdb_file: templates/CBP.pdb
          itp_file: templates/CBP.itp
          ratio: 42
        IPR:
          res_name: IPR
          pdb_file: templates/IPR.pdb      
          itp_file: templates/IPR.itp
          ratio: 1
        IPS:
          res_name: IPS
          pdb_file: templates/IPS.pdb      
          itp_file: templates/IPS.itp
          ratio: 1
  - description: 'Deposition of a second layer of 200 XXX (~2nm high) molecules'
    first_sim_id: 1002
    last_sim_id: 1202
    run_time: 10.0 #ps
    temperature: 300
    mixture:
        BCP:
          res_name: BCP
          pdb_file: templates/BCP.pdb
          itp_file: templates/BCP.itp
          ratio: 1
substrate: 
      res_name: GRP
      pdb_file: templates/GRP.pdb
      itp_file: templates/GRP.itp
movies:
    n_cores: 8
