name: MPI_solvent_example
work_directory: MPI_solvent_example_working
initial_structure_file: systems/test_solvent_evaporation.gro
simulation_type: solvent_evaporation
solvent_name: CCL3
n_cycles: 1
forcefield_file: gromos54a7_atb.ff/forcefield.itp
description: 'Simple example of solvent evaporation of CBP/Ir(ppy)3/CCL3.'
run_time: 10 #ps
nstout: 100000
seed: 1718831
temperature: 310 #K
gmx_executable: gmx_mpi_d
mpi_template : "srun -N $SLURM_JOB_NUM_NODES -n $NRANK -c $OMP_NUM_THREADS -m block:block:block"
mdrun_template: "{GMX_EXEC} mdrun -s {tpr} -x {xtc} -e {edr} -g {log} -cpo {cpo} -c {final}"
mixture:
  CBP:
    res_name: CBP
    itp_file: systems/CBP.itp
  IPS:
    res_name: IPAS
    itp_file: systems/IPAS.itp
  IPR:
    res_name: IPAR
    itp_file: systems/IPAR.itp
  CCL3:
    res_name: CCL3
    itp_file: systems/CHCL3.itp
substrate: 
    res_name: GRM
    itp_file: systems/GRM.itp
