name: annealing_example
work_directory: annealing_example_working
initial_structure_file: systems/test_annealing.gro
simulation_type: thermal_annealing
forcefield_file: gromos54a7_atb.ff/forcefield.itp
description: 'Example of very short annealing of CBP/Ir(ppy)3 [R and S] system'
run_time: 1.0 #ps
nstout: 100
seed: 142271835
temperature_list:
  - 400
  - 380
  - 360
  - 340
  - 320
  - 300
mixture:
  CBP:
    res_name: CBP
    itp_file: systems/CBP.itp
  IPS:
    res_name: IPAS
    itp_file: systems/IPAS.itp
  IPR:
    res_name: IPAR
    itp_file: systems/IPAR.itp
substrate: 
    res_name: GRM
    itp_file: systems/GRM.itp
