#/bin/bash
#PBS -P n62
#PBS -M c.tonnele@uq.edu.au
#PBS -m abe
#PBS -q express
#PBS -l ncpus=8
#PBS -l mem=8gb
#PBS -l walltime=00:30:00
#PBS -l software=gromacs407
#PBS -l other=mpi
#PBS -l wd
#PBS -N gph80cbp<%= ENV['n'] %>


#==============================================================
#                  Script  for  NCI
#==============================================================
module load gromacs/4.0.7

grompp_d -f run.mdp -c cbp<%=ENV['n']%>-init.pdb -p topo.top -o md.tpr

module load openmpi

mpirun -np 8 --bind-to-none mdrun_mpi_d -np 8 -pd -s md.tpr -deffnm md -c cbp<%=ENV['n']%>-end.pdb


